server:
  port: '8080'

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/tic-tac-toe
    password: root

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
